// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ceffo/mrboard/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSnapshotStore creates a new instance of MockSnapshotStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnapshotStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnapshotStore {
	mock := &MockSnapshotStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSnapshotStore is an autogenerated mock type for the SnapshotStore type
type MockSnapshotStore struct {
	mock.Mock
}

type MockSnapshotStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnapshotStore) EXPECT() *MockSnapshotStore_Expecter {
	return &MockSnapshotStore_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockSnapshotStore
func (_mock *MockSnapshotStore) Load() ([]domain.MergeRequest, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []domain.MergeRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]domain.MergeRequest, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []domain.MergeRequest); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MergeRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnapshotStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockSnapshotStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockSnapshotStore_Expecter) Load() *MockSnapshotStore_Load_Call {
	return &MockSnapshotStore_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockSnapshotStore_Load_Call) Run(run func()) *MockSnapshotStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSnapshotStore_Load_Call) Return(mergeRequests []domain.MergeRequest, err error) *MockSnapshotStore_Load_Call {
	_c.Call.Return(mergeRequests, err)
	return _c
}

func (_c *MockSnapshotStore_Load_Call) RunAndReturn(run func() ([]domain.MergeRequest, error)) *MockSnapshotStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockSnapshotStore
func (_mock *MockSnapshotStore) Save(mergeRequests []domain.MergeRequest) error {
	ret := _mock.Called(mergeRequests)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]domain.MergeRequest) error); ok {
		r0 = returnFunc(mergeRequests)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSnapshotStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSnapshotStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - mergeRequests []domain.MergeRequest
func (_e *MockSnapshotStore_Expecter) Save(mergeRequests any) *MockSnapshotStore_Save_Call {
	return &MockSnapshotStore_Save_Call{Call: _e.mock.On("Save", mergeRequests)}
}

func (_c *MockSnapshotStore_Save_Call) Run(run func(mergeRequests []domain.MergeRequest)) *MockSnapshotStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []domain.MergeRequest
		if args[0] != nil {
			arg0 = args[0].([]domain.MergeRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSnapshotStore_Save_Call) Return(err error) *MockSnapshotStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSnapshotStore_Save_Call) RunAndReturn(run func(mergeRequests []domain.MergeRequest) error) *MockSnapshotStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
