// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockJiraEnricher creates a new instance of MockJiraEnricher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJiraEnricher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJiraEnricher {
	mock := &MockJiraEnricher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJiraEnricher is an autogenerated mock type for the JiraEnricher type
type MockJiraEnricher struct {
	mock.Mock
}

type MockJiraEnricher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJiraEnricher) EXPECT() *MockJiraEnricher_Expecter {
	return &MockJiraEnricher_Expecter{mock: &_m.Mock}
}

// GetActiveSprintIssueKeys provides a mock function for the type MockJiraEnricher
func (_mock *MockJiraEnricher) GetActiveSprintIssueKeys(ctx context.Context, boardID int) ([]string, error) {
	ret := _mock.Called(ctx, boardID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSprintIssueKeys")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]string, error)); ok {
		return returnFunc(ctx, boardID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = returnFunc(ctx, boardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, boardID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJiraEnricher_GetActiveSprintIssueKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveSprintIssueKeys'
type MockJiraEnricher_GetActiveSprintIssueKeys_Call struct {
	*mock.Call
}

// GetActiveSprintIssueKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - boardID int
func (_e *MockJiraEnricher_Expecter) GetActiveSprintIssueKeys(ctx any, boardID any) *MockJiraEnricher_GetActiveSprintIssueKeys_Call {
	return &MockJiraEnricher_GetActiveSprintIssueKeys_Call{Call: _e.mock.On("GetActiveSprintIssueKeys", ctx, boardID)}
}

func (_c *MockJiraEnricher_GetActiveSprintIssueKeys_Call) Run(run func(ctx context.Context, boardID int)) *MockJiraEnricher_GetActiveSprintIssueKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJiraEnricher_GetActiveSprintIssueKeys_Call) Return(strings []string, err error) *MockJiraEnricher_GetActiveSprintIssueKeys_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockJiraEnricher_GetActiveSprintIssueKeys_Call) RunAndReturn(run func(ctx context.Context, boardID int) ([]string, error)) *MockJiraEnricher_GetActiveSprintIssueKeys_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssueType provides a mock function for the type MockJiraEnricher
func (_mock *MockJiraEnricher) GetIssueType(ctx context.Context, issueKey string) (string, error) {
	ret := _mock.Called(ctx, issueKey)

	if len(ret) == 0 {
		panic("no return value specified for GetIssueType")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, issueKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, issueKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, issueKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJiraEnricher_GetIssueType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssueType'
type MockJiraEnricher_GetIssueType_Call struct {
	*mock.Call
}

// GetIssueType is a helper method to define mock.On call
//   - ctx context.Context
//   - issueKey string
func (_e *MockJiraEnricher_Expecter) GetIssueType(ctx any, issueKey any) *MockJiraEnricher_GetIssueType_Call {
	return &MockJiraEnricher_GetIssueType_Call{Call: _e.mock.On("GetIssueType", ctx, issueKey)}
}

func (_c *MockJiraEnricher_GetIssueType_Call) Run(run func(ctx context.Context, issueKey string)) *MockJiraEnricher_GetIssueType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJiraEnricher_GetIssueType_Call) Return(s string, err error) *MockJiraEnricher_GetIssueType_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJiraEnricher_GetIssueType_Call) RunAndReturn(run func(ctx context.Context, issueKey string) (string, error)) *MockJiraEnricher_GetIssueType_Call {
	_c.Call.Return(run)
	return _c
}
