// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/mrboard/mrboard/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMergeRequestSource creates a new instance of MockMergeRequestSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMergeRequestSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMergeRequestSource {
	mock := &MockMergeRequestSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMergeRequestSource is an autogenerated mock type for the MergeRequestSource type
type MockMergeRequestSource struct {
	mock.Mock
}

type MockMergeRequestSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMergeRequestSource) EXPECT() *MockMergeRequestSource_Expecter {
	return &MockMergeRequestSource_Expecter{mock: &_m.Mock}
}

// FetchAll provides a mock function for the type MockMergeRequestSource
func (_mock *MockMergeRequestSource) FetchAll() ([]domain.MergeRequest, []error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchAll")
	}

	var r0 []domain.MergeRequest
	var r1 []error
	if returnFunc, ok := ret.Get(0).(func() ([]domain.MergeRequest, []error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []domain.MergeRequest); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MergeRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() []error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}
	return r0, r1
}

// MockMergeRequestSource_FetchAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAll'
type MockMergeRequestSource_FetchAll_Call struct {
	*mock.Call
}

// FetchAll is a helper method to define mock.On call
func (_e *MockMergeRequestSource_Expecter) FetchAll() *MockMergeRequestSource_FetchAll_Call {
	return &MockMergeRequestSource_FetchAll_Call{Call: _e.mock.On("FetchAll")}
}

func (_c *MockMergeRequestSource_FetchAll_Call) Run(run func()) *MockMergeRequestSource_FetchAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMergeRequestSource_FetchAll_Call) Return(mergeRequests []domain.MergeRequest, errs []error) *MockMergeRequestSource_FetchAll_Call {
	_c.Call.Return(mergeRequests, errs)
	return _c
}

func (_c *MockMergeRequestSource_FetchAll_Call) RunAndReturn(run func() ([]domain.MergeRequest, []error)) *MockMergeRequestSource_FetchAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetail provides a mock function for the type MockMergeRequestSource
func (_mock *MockMergeRequestSource) GetDetail(projectID int64, mrIID int64) (string, []domain.Thread, error) {
	ret := _mock.Called(projectID, mrIID)

	if len(ret) == 0 {
		panic("no return value specified for GetDetail")
	}

	var r0 string
	var r1 []domain.Thread
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64) (string, []domain.Thread, error)); ok {
		return returnFunc(projectID, mrIID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, int64) string); ok {
		r0 = returnFunc(projectID, mrIID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, int64) []domain.Thread); ok {
		r1 = returnFunc(projectID, mrIID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]domain.Thread)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(int64, int64) error); ok {
		r2 = returnFunc(projectID, mrIID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMergeRequestSource_GetDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetail'
type MockMergeRequestSource_GetDetail_Call struct {
	*mock.Call
}

// GetDetail is a helper method to define mock.On call
//   - projectID int64
//   - mrIID int64
func (_e *MockMergeRequestSource_Expecter) GetDetail(projectID interface{}, mrIID interface{}) *MockMergeRequestSource_GetDetail_Call {
	return &MockMergeRequestSource_GetDetail_Call{Call: _e.mock.On("GetDetail", projectID, mrIID)}
}

func (_c *MockMergeRequestSource_GetDetail_Call) Run(run func(projectID int64, mrIID int64)) *MockMergeRequestSource_GetDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMergeRequestSource_GetDetail_Call) Return(description string, threads []domain.Thread, err error) *MockMergeRequestSource_GetDetail_Call {
	_c.Call.Return(description, threads, err)
	return _c
}

func (_c *MockMergeRequestSource_GetDetail_Call) RunAndReturn(run func(projectID int64, mrIID int64) (string, []domain.Thread, error)) *MockMergeRequestSource_GetDetail_Call {
	_c.Call.Return(run)
	return _c
}
