// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTicketEnricher creates a new instance of MockTicketEnricher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketEnricher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketEnricher {
	mock := &MockTicketEnricher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTicketEnricher is an autogenerated mock type for the TicketEnricher type
type MockTicketEnricher struct {
	mock.Mock
}

type MockTicketEnricher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketEnricher) EXPECT() *MockTicketEnricher_Expecter {
	return &MockTicketEnricher_Expecter{mock: &_m.Mock}
}

// GetActiveSprintIssueKeys provides a mock function for the type MockTicketEnricher
func (_mock *MockTicketEnricher) GetActiveSprintIssueKeys(ctx context.Context, boardID int, forceRefresh bool) ([]string, error) {
	ret := _mock.Called(ctx, boardID, forceRefresh)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSprintIssueKeys")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) ([]string, error)); ok {
		return returnFunc(ctx, boardID, forceRefresh)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) []string); ok {
		r0 = returnFunc(ctx, boardID, forceRefresh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, bool) error); ok {
		r1 = returnFunc(ctx, boardID, forceRefresh)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketEnricher_GetActiveSprintIssueKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveSprintIssueKeys'
type MockTicketEnricher_GetActiveSprintIssueKeys_Call struct {
	*mock.Call
}

// GetActiveSprintIssueKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - boardID int
//   - forceRefresh bool
func (_e *MockTicketEnricher_Expecter) GetActiveSprintIssueKeys(ctx any, boardID any, forceRefresh any) *MockTicketEnricher_GetActiveSprintIssueKeys_Call {
	return &MockTicketEnricher_GetActiveSprintIssueKeys_Call{Call: _e.mock.On("GetActiveSprintIssueKeys", ctx, boardID, forceRefresh)}
}

func (_c *MockTicketEnricher_GetActiveSprintIssueKeys_Call) Run(run func(ctx context.Context, boardID int, forceRefresh bool)) *MockTicketEnricher_GetActiveSprintIssueKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTicketEnricher_GetActiveSprintIssueKeys_Call) Return(strings []string, err error) *MockTicketEnricher_GetActiveSprintIssueKeys_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockTicketEnricher_GetActiveSprintIssueKeys_Call) RunAndReturn(run func(ctx context.Context, boardID int, forceRefresh bool) ([]string, error)) *MockTicketEnricher_GetActiveSprintIssueKeys_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssueType provides a mock function for the type MockTicketEnricher
func (_mock *MockTicketEnricher) GetIssueType(ctx context.Context, issueKey string) (string, error) {
	ret := _mock.Called(ctx, issueKey)

	if len(ret) == 0 {
		panic("no return value specified for GetIssueType")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, issueKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, issueKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, issueKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketEnricher_GetIssueType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssueType'
type MockTicketEnricher_GetIssueType_Call struct {
	*mock.Call
}

// GetIssueType is a helper method to define mock.On call
//   - ctx context.Context
//   - issueKey string
func (_e *MockTicketEnricher_Expecter) GetIssueType(ctx any, issueKey any) *MockTicketEnricher_GetIssueType_Call {
	return &MockTicketEnricher_GetIssueType_Call{Call: _e.mock.On("GetIssueType", ctx, issueKey)}
}

func (_c *MockTicketEnricher_GetIssueType_Call) Run(run func(ctx context.Context, issueKey string)) *MockTicketEnricher_GetIssueType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketEnricher_GetIssueType_Call) Return(s string, err error) *MockTicketEnricher_GetIssueType_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTicketEnricher_GetIssueType_Call) RunAndReturn(run func(ctx context.Context, issueKey string) (string, error)) *MockTicketEnricher_GetIssueType_Call {
	_c.Call.Return(run)
	return _c
}
