// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTicketLinker creates a new instance of MockTicketLinker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketLinker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketLinker {
	mock := &MockTicketLinker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTicketLinker is an autogenerated mock type for the TicketLinker type
type MockTicketLinker struct {
	mock.Mock
}

type MockTicketLinker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketLinker) EXPECT() *MockTicketLinker_Expecter {
	return &MockTicketLinker_Expecter{mock: &_m.Mock}
}

// UpsertRemoteLink provides a mock function for the type MockTicketLinker
func (_mock *MockTicketLinker) UpsertRemoteLink(ctx context.Context, issueKey string, globalID string, mrTitle string, mrURL string) error {
	ret := _mock.Called(ctx, issueKey, globalID, mrTitle, mrURL)

	if len(ret) == 0 {
		panic("no return value specified for UpsertRemoteLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, issueKey, globalID, mrTitle, mrURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketLinker_UpsertRemoteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertRemoteLink'
type MockTicketLinker_UpsertRemoteLink_Call struct {
	*mock.Call
}

// UpsertRemoteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - issueKey string
//   - globalID string
//   - mrTitle string
//   - mrURL string
func (_e *MockTicketLinker_Expecter) UpsertRemoteLink(ctx any, issueKey any, globalID any, mrTitle any, mrURL any) *MockTicketLinker_UpsertRemoteLink_Call {
	return &MockTicketLinker_UpsertRemoteLink_Call{Call: _e.mock.On("UpsertRemoteLink", ctx, issueKey, globalID, mrTitle, mrURL)}
}

func (_c *MockTicketLinker_UpsertRemoteLink_Call) Run(run func(ctx context.Context, issueKey string, globalID string, mrTitle string, mrURL string)) *MockTicketLinker_UpsertRemoteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTicketLinker_UpsertRemoteLink_Call) Return(err error) *MockTicketLinker_UpsertRemoteLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketLinker_UpsertRemoteLink_Call) RunAndReturn(run func(ctx context.Context, issueKey string, globalID string, mrTitle string, mrURL string) error) *MockTicketLinker_UpsertRemoteLink_Call {
	_c.Call.Return(run)
	return _c
}
