// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ceffo/mrboard/internal/domain/service/updatesvc"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUpdateChecker creates a new instance of MockUpdateChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateChecker {
	mock := &MockUpdateChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdateChecker is an autogenerated mock type for the UpdateChecker type
type MockUpdateChecker struct {
	mock.Mock
}

type MockUpdateChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateChecker) EXPECT() *MockUpdateChecker_Expecter {
	return &MockUpdateChecker_Expecter{mock: &_m.Mock}
}

// CheckForUpdate provides a mock function for the type MockUpdateChecker
func (_mock *MockUpdateChecker) CheckForUpdate(ctx context.Context, currentVersion string) (updatesvc.Info, error) {
	ret := _mock.Called(ctx, currentVersion)

	if len(ret) == 0 {
		panic("no return value specified for CheckForUpdate")
	}

	var r0 updatesvc.Info
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (updatesvc.Info, error)); ok {
		return returnFunc(ctx, currentVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) updatesvc.Info); ok {
		r0 = returnFunc(ctx, currentVersion)
	} else {
		r0 = ret.Get(0).(updatesvc.Info)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, currentVersion)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdateChecker_CheckForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckForUpdate'
type MockUpdateChecker_CheckForUpdate_Call struct {
	*mock.Call
}

// CheckForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - currentVersion string
func (_e *MockUpdateChecker_Expecter) CheckForUpdate(ctx any, currentVersion any) *MockUpdateChecker_CheckForUpdate_Call {
	return &MockUpdateChecker_CheckForUpdate_Call{Call: _e.mock.On("CheckForUpdate", ctx, currentVersion)}
}

func (_c *MockUpdateChecker_CheckForUpdate_Call) Run(run func(ctx context.Context, currentVersion string)) *MockUpdateChecker_CheckForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUpdateChecker_CheckForUpdate_Call) Return(info updatesvc.Info, err error) *MockUpdateChecker_CheckForUpdate_Call {
	_c.Call.Return(info, err)
	return _c
}

func (_c *MockUpdateChecker_CheckForUpdate_Call) RunAndReturn(run func(ctx context.Context, currentVersion string) (updatesvc.Info, error)) *MockUpdateChecker_CheckForUpdate_Call {
	_c.Call.Return(run)
	return _c
}
