// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ceffo/mrboard/internal/domain/service/mrsvc"
	mock "github.com/stretchr/testify/mock"
)

// NewMockApproverClaims creates a new instance of MockApproverClaims. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApproverClaims(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApproverClaims {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockApproverClaims{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockApproverClaims is an autogenerated mock type for the ApproverClaims type
type MockApproverClaims struct {
	mock.Mock
}

type MockApproverClaims_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApproverClaims) EXPECT() *MockApproverClaims_Expecter {
	return &MockApproverClaims_Expecter{mock: &_m.Mock}
}

// Claim provides a mock function for the type MockApproverClaims
func (_mock *MockApproverClaims) Claim(ctx context.Context, req mrsvc.ClaimRequest) (bool, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Claim")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mrsvc.ClaimRequest) (bool, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mrsvc.ClaimRequest) bool); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mrsvc.ClaimRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApproverClaims_Claim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claim'
type MockApproverClaims_Claim_Call struct {
	*mock.Call
}

// Claim is a helper method to define mock.On call
//   - ctx context.Context
//   - req mrsvc.ClaimRequest
func (_e *MockApproverClaims_Expecter) Claim(ctx any, req any) *MockApproverClaims_Claim_Call {
	return &MockApproverClaims_Claim_Call{Call: _e.mock.On("Claim", ctx, req)}
}

func (_c *MockApproverClaims_Claim_Call) Run(run func(ctx context.Context, req mrsvc.ClaimRequest)) *MockApproverClaims_Claim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mrsvc.ClaimRequest
		if args[1] != nil {
			arg1 = args[1].(mrsvc.ClaimRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApproverClaims_Claim_Call) Return(owned bool, err error) *MockApproverClaims_Claim_Call {
	_c.Call.Return(owned, err)
	return _c
}

func (_c *MockApproverClaims_Claim_Call) RunAndReturn(run func(ctx context.Context, req mrsvc.ClaimRequest) (bool, error)) *MockApproverClaims_Claim_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type MockApproverClaims
func (_mock *MockApproverClaims) Release(ctx context.Context, projectID int64, mrIID int64, approvers []string) error {
	ret := _mock.Called(ctx, projectID, mrIID, approvers)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, []string) error); ok {
		r0 = returnFunc(ctx, projectID, mrIID, approvers)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApproverClaims_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockApproverClaims_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
//   - mrIID int64
//   - approvers []string
func (_e *MockApproverClaims_Expecter) Release(ctx any, projectID any, mrIID any, approvers any) *MockApproverClaims_Release_Call {
	return &MockApproverClaims_Release_Call{Call: _e.mock.On("Release", ctx, projectID, mrIID, approvers)}
}

func (_c *MockApproverClaims_Release_Call) Run(run func(ctx context.Context, projectID int64, mrIID int64, approvers []string)) *MockApproverClaims_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockApproverClaims_Release_Call) Return(err error) *MockApproverClaims_Release_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApproverClaims_Release_Call) RunAndReturn(run func(ctx context.Context, projectID int64, mrIID int64, approvers []string) error) *MockApproverClaims_Release_Call {
	_c.Call.Return(run)
	return _c
}
